/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "TR103562v211-CPM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -R`
 */

#include "AreaRectangle.h"

static asn_TYPE_member_t asn_MBR_AreaRectangle_1[] = {
	{ ATF_POINTER, 1, offsetof(struct AreaRectangle, nodeCenterPoint),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OffsetPoint,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"nodeCenterPoint"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AreaRectangle, semiMajorRangeLength),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SemiRangeLength,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"semiMajorRangeLength"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AreaRectangle, semiMinorRangeLength),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SemiRangeLength,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"semiMinorRangeLength"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AreaRectangle, semiMajorRangeOrientation),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_WGS84AngleValue,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"semiMajorRangeOrientation"
		},
	{ ATF_POINTER, 1, offsetof(struct AreaRectangle, semiHeight),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SemiRangeLength,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"semiHeight"
		},
};
static const ber_tlv_tag_t asn_DEF_AreaRectangle_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_AreaRectangle_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* nodeCenterPoint */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* semiMajorRangeLength */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* semiMinorRangeLength */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* semiMajorRangeOrientation */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* semiHeight */
};
static asn_SEQUENCE_specifics_t asn_SPC_AreaRectangle_specs_1 = {
	sizeof(struct AreaRectangle),
	offsetof(struct AreaRectangle, _asn_ctx),
	asn_MAP_AreaRectangle_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_AreaRectangle = {
	"AreaRectangle",
	"AreaRectangle",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_AreaRectangle_tags_1,
	sizeof(asn_DEF_AreaRectangle_tags_1)
		/sizeof(asn_DEF_AreaRectangle_tags_1[0]), /* 1 */
	asn_DEF_AreaRectangle_tags_1,	/* Same as above */
	sizeof(asn_DEF_AreaRectangle_tags_1)
		/sizeof(asn_DEF_AreaRectangle_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_AreaRectangle_1,
	5,	/* Elements count */
	&asn_SPC_AreaRectangle_specs_1	/* Additional specs */
};

