/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "TR103562v211-CPM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -R`
 */

#ifndef	_AreaPolygon_H_
#define	_AreaPolygon_H_


#include "asn_application.h"

/* Including external dependencies */
#include "PolyPointList.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* AreaPolygon */
typedef struct AreaPolygon {
	PolyPointList_t	 polyPointList;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AreaPolygon_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AreaPolygon;

#ifdef __cplusplus
}
#endif

#endif	/* _AreaPolygon_H_ */
#include "asn_internal.h"
