/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "TR103562v211-CPM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -R`
 */

#ifndef	_AreaCircular_H_
#define	_AreaCircular_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Radius.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct OffsetPoint;

/* AreaCircular */
typedef struct AreaCircular {
	struct OffsetPoint	*nodeCenterPoint	/* OPTIONAL */;
	Radius_t	 radius;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AreaCircular_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AreaCircular;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "OffsetPoint.h"

#endif	/* _AreaCircular_H_ */
#include "asn_internal.h"
