/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "TR103562v211-CPM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -R`
 */

#ifndef	_AreaEllipse_H_
#define	_AreaEllipse_H_


#include "asn_application.h"

/* Including external dependencies */
#include "SemiRangeLength.h"
#include "WGS84AngleValue.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct OffsetPoint;

/* AreaEllipse */
typedef struct AreaEllipse {
	struct OffsetPoint	*nodeCenterPoint	/* OPTIONAL */;
	SemiRangeLength_t	 semiMinorRangeLength;
	SemiRangeLength_t	 semiMajorRangeLength;
	WGS84AngleValue_t	 semiMajorRangeOrientation;
	SemiRangeLength_t	*semiHeight	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AreaEllipse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AreaEllipse;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "OffsetPoint.h"

#endif	/* _AreaEllipse_H_ */
#include "asn_internal.h"
