/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "TR103562v211-CPM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -R`
 */

#ifndef	_CollectivePerceptionMessage_H_
#define	_CollectivePerceptionMessage_H_


#include "asn_application.h"

/* Including external dependencies */
#include "GenerationDeltaTime.h"
#include "CpmParameters.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* CollectivePerceptionMessage */
typedef struct CollectivePerceptionMessage {
	GenerationDeltaTime_t	 generationDeltaTime;
	CpmParameters_t	 cpmParameters;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CollectivePerceptionMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CollectivePerceptionMessage;

#ifdef __cplusplus
}
#endif

#endif	/* _CollectivePerceptionMessage_H_ */
#include "asn_internal.h"
