/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "PriMa-MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -R`
 */

#ifndef	_CooperationCostTrajectory_H_
#define	_CooperationCostTrajectory_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* CooperationCostTrajectory */
typedef long	 CooperationCostTrajectory_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CooperationCostTrajectory;
asn_struct_free_f CooperationCostTrajectory_free;
asn_struct_print_f CooperationCostTrajectory_print;
asn_constr_check_f CooperationCostTrajectory_constraint;
ber_type_decoder_f CooperationCostTrajectory_decode_ber;
der_type_encoder_f CooperationCostTrajectory_encode_der;
xer_type_decoder_f CooperationCostTrajectory_decode_xer;
xer_type_encoder_f CooperationCostTrajectory_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _CooperationCostTrajectory_H_ */
#include "asn_internal.h"
