/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "PriMa-MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -R`
 */

#ifndef	_CooperationTypeMCM_H_
#define	_CooperationTypeMCM_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CooperationTypeMCM {
	CooperationTypeMCM_agreementSeeking	= 0,
	CooperationTypeMCM_prescriptive	= 1,
	CooperationTypeMCM_interceptionLevel	= 2,
	CooperationTypeMCM_roadSafetyLevel	= 3
} e_CooperationTypeMCM;

/* CooperationTypeMCM */
typedef long	 CooperationTypeMCM_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CooperationTypeMCM;
asn_struct_free_f CooperationTypeMCM_free;
asn_struct_print_f CooperationTypeMCM_print;
asn_constr_check_f CooperationTypeMCM_constraint;
ber_type_decoder_f CooperationTypeMCM_decode_ber;
der_type_encoder_f CooperationTypeMCM_encode_der;
xer_type_decoder_f CooperationTypeMCM_decode_xer;
xer_type_encoder_f CooperationTypeMCM_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _CooperationTypeMCM_H_ */
#include "asn_internal.h"
