/*
 * Generated by asn1c; locally adapted to Vanetza's current ASN.1 descriptor ABI.
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "PriMa-MCM.asn"
 */

#include "CooperationID.h"

static const ber_tlv_tag_t asn_DEF_CooperationID_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (2 << 2))
};
asn_TYPE_descriptor_t asn_DEF_CooperationID = {
	"CooperationID",
	"CooperationID",
	&asn_OP_NativeInteger,
	asn_DEF_CooperationID_tags_1,
	sizeof(asn_DEF_CooperationID_tags_1)
		/sizeof(asn_DEF_CooperationID_tags_1[0]), /* 1 */
	asn_DEF_CooperationID_tags_1,	/* Same as above */
	sizeof(asn_DEF_CooperationID_tags_1)
		/sizeof(asn_DEF_CooperationID_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		0
	},
	0, 0,	/* Defined elsewhere */
	0	/* No specifics */
};
