/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "TR103562v211-CPM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -R`
 */

#ifndef	_CpmManagementContainer_H_
#define	_CpmManagementContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "StationType.h"
#include "ReferencePosition.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PerceivedObjectContainerSegmentInfo;

/* CpmManagementContainer */
typedef struct CpmManagementContainer {
	StationType_t	 stationType;
	struct PerceivedObjectContainerSegmentInfo	*perceivedObjectContainerSegmentInfo	/* OPTIONAL */;
	ReferencePosition_t	 referencePosition;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CpmManagementContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CpmManagementContainer;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PerceivedObjectContainerSegmentInfo.h"

#endif	/* _CpmManagementContainer_H_ */
#include "asn_internal.h"
