/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "TR103562v211-CPM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -R`
 */

#ifndef	_CpmParameters_H_
#define	_CpmParameters_H_


#include "asn_application.h"

/* Including external dependencies */
#include "CpmManagementContainer.h"
#include "NumberOfPerceivedObjects.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct StationDataContainer;
struct SensorInformationContainer;
struct PerceivedObjectContainer;
struct FreeSpaceAddendumContainer;

/* CpmParameters */
typedef struct CpmParameters {
	CpmManagementContainer_t	 managementContainer;
	struct StationDataContainer	*stationDataContainer	/* OPTIONAL */;
	struct SensorInformationContainer	*sensorInformationContainer	/* OPTIONAL */;
	struct PerceivedObjectContainer	*perceivedObjectContainer	/* OPTIONAL */;
	struct FreeSpaceAddendumContainer	*freeSpaceAddendumContainer	/* OPTIONAL */;
	NumberOfPerceivedObjects_t	 numberOfPerceivedObjects;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CpmParameters_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CpmParameters;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "StationDataContainer.h"
#include "SensorInformationContainer.h"
#include "PerceivedObjectContainer.h"
#include "FreeSpaceAddendumContainer.h"

#endif	/* _CpmParameters_H_ */
#include "asn_internal.h"
