/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "TR103562v211-CPM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -R`
 */

#include "CpmParameters.h"

static asn_TYPE_member_t asn_MBR_CpmParameters_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CpmParameters, managementContainer),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CpmManagementContainer,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"managementContainer"
		},
	{ ATF_POINTER, 4, offsetof(struct CpmParameters, stationDataContainer),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_StationDataContainer,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"stationDataContainer"
		},
	{ ATF_POINTER, 3, offsetof(struct CpmParameters, sensorInformationContainer),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SensorInformationContainer,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"sensorInformationContainer"
		},
	{ ATF_POINTER, 2, offsetof(struct CpmParameters, perceivedObjectContainer),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PerceivedObjectContainer,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"perceivedObjectContainer"
		},
	{ ATF_POINTER, 1, offsetof(struct CpmParameters, freeSpaceAddendumContainer),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_FreeSpaceAddendumContainer,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"freeSpaceAddendumContainer"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CpmParameters, numberOfPerceivedObjects),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NumberOfPerceivedObjects,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"numberOfPerceivedObjects"
		},
};
static const ber_tlv_tag_t asn_DEF_CpmParameters_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_CpmParameters_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* managementContainer */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* stationDataContainer */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* sensorInformationContainer */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* perceivedObjectContainer */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* freeSpaceAddendumContainer */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* numberOfPerceivedObjects */
};
static asn_SEQUENCE_specifics_t asn_SPC_CpmParameters_specs_1 = {
	sizeof(struct CpmParameters),
	offsetof(struct CpmParameters, _asn_ctx),
	asn_MAP_CpmParameters_tag2el_1,
	6,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	5,	/* Start extensions */
	7	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_CpmParameters = {
	"CpmParameters",
	"CpmParameters",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_CpmParameters_tags_1,
	sizeof(asn_DEF_CpmParameters_tags_1)
		/sizeof(asn_DEF_CpmParameters_tags_1[0]), /* 1 */
	asn_DEF_CpmParameters_tags_1,	/* Same as above */
	sizeof(asn_DEF_CpmParameters_tags_1)
		/sizeof(asn_DEF_CpmParameters_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_CpmParameters_1,
	6,	/* Elements count */
	&asn_SPC_CpmParameters_specs_1	/* Additional specs */
};

