/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "TR103562v211-CPM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -R`
 */

#include "DetectionArea.h"

static asn_TYPE_member_t asn_MBR_DetectionArea_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DetectionArea, choice.vehicleSensor),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VehicleSensor,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"vehicleSensor"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DetectionArea, choice.stationarySensorRadial),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AreaRadial,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"stationarySensorRadial"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DetectionArea, choice.stationarySensorPolygon),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AreaPolygon,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"stationarySensorPolygon"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DetectionArea, choice.stationarySensorCircular),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AreaCircular,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"stationarySensorCircular"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DetectionArea, choice.stationarySensorEllipse),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AreaEllipse,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"stationarySensorEllipse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DetectionArea, choice.stationarySensorRectangle),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AreaRectangle,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"stationarySensorRectangle"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_DetectionArea_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* vehicleSensor */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* stationarySensorRadial */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* stationarySensorPolygon */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* stationarySensorCircular */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* stationarySensorEllipse */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* stationarySensorRectangle */
};
static asn_CHOICE_specifics_t asn_SPC_DetectionArea_specs_1 = {
	sizeof(struct DetectionArea),
	offsetof(struct DetectionArea, _asn_ctx),
	offsetof(struct DetectionArea, present),
	sizeof(((struct DetectionArea *)0)->present),
	asn_MAP_DetectionArea_tag2el_1,
	6,	/* Count of tags in the map */
	0,
	6	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_DetectionArea = {
	"DetectionArea",
	"DetectionArea",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_DetectionArea_1,
	6,	/* Elements count */
	&asn_SPC_DetectionArea_specs_1	/* Additional specs */
};

