/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "TR103562v211-CPM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -R`
 */

#ifndef	_DistanceConfidence_H_
#define	_DistanceConfidence_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DistanceConfidence {
	DistanceConfidence_zeroPointZeroOneMeter	= 1,
	DistanceConfidence_oneMeter	= 100,
	DistanceConfidence_outOfRange	= 101,
	DistanceConfidence_unavailable	= 102
} e_DistanceConfidence;

/* DistanceConfidence */
typedef long	 DistanceConfidence_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DistanceConfidence;
asn_struct_free_f DistanceConfidence_free;
asn_struct_print_f DistanceConfidence_print;
asn_constr_check_f DistanceConfidence_constraint;
ber_type_decoder_f DistanceConfidence_decode_ber;
der_type_encoder_f DistanceConfidence_encode_der;
xer_type_decoder_f DistanceConfidence_decode_xer;
xer_type_encoder_f DistanceConfidence_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DistanceConfidence_H_ */
#include "asn_internal.h"
