/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "TR103562v211-CPM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -R`
 */

#include "FreeSpaceAddendum.h"

static asn_TYPE_member_t asn_MBR_FreeSpaceAddendum_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct FreeSpaceAddendum, freeSpaceConfidence),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_FreeSpaceConfidence,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"freeSpaceConfidence"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct FreeSpaceAddendum, freeSpaceArea),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_FreeSpaceArea,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"freeSpaceArea"
		},
	{ ATF_POINTER, 2, offsetof(struct FreeSpaceAddendum, sensorIDList),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SensorIdList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"sensorIDList"
		},
	{ ATF_POINTER, 1, offsetof(struct FreeSpaceAddendum, shadowingApplies),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ShadowingApplies,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"shadowingApplies"
		},
};
static const ber_tlv_tag_t asn_DEF_FreeSpaceAddendum_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_FreeSpaceAddendum_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* freeSpaceConfidence */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* freeSpaceArea */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* sensorIDList */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* shadowingApplies */
};
static asn_SEQUENCE_specifics_t asn_SPC_FreeSpaceAddendum_specs_1 = {
	sizeof(struct FreeSpaceAddendum),
	offsetof(struct FreeSpaceAddendum, _asn_ctx),
	asn_MAP_FreeSpaceAddendum_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	3,	/* Start extensions */
	5	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_FreeSpaceAddendum = {
	"FreeSpaceAddendum",
	"FreeSpaceAddendum",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_FreeSpaceAddendum_tags_1,
	sizeof(asn_DEF_FreeSpaceAddendum_tags_1)
		/sizeof(asn_DEF_FreeSpaceAddendum_tags_1[0]), /* 1 */
	asn_DEF_FreeSpaceAddendum_tags_1,	/* Same as above */
	sizeof(asn_DEF_FreeSpaceAddendum_tags_1)
		/sizeof(asn_DEF_FreeSpaceAddendum_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_FreeSpaceAddendum_1,
	4,	/* Elements count */
	&asn_SPC_FreeSpaceAddendum_specs_1	/* Additional specs */
};

