/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "TR103562v211-CPM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -R`
 */

#ifndef	_HitchPointOffset_H_
#define	_HitchPointOffset_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum HitchPointOffset {
	HitchPointOffset_zeroPointOneMeter	= 1,
	HitchPointOffset_oneMeter	= 10
} e_HitchPointOffset;

/* HitchPointOffset */
typedef long	 HitchPointOffset_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HitchPointOffset;
asn_struct_free_f HitchPointOffset_free;
asn_struct_print_f HitchPointOffset_print;
asn_constr_check_f HitchPointOffset_constraint;
ber_type_decoder_f HitchPointOffset_decode_ber;
der_type_encoder_f HitchPointOffset_encode_der;
xer_type_decoder_f HitchPointOffset_decode_xer;
xer_type_encoder_f HitchPointOffset_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _HitchPointOffset_H_ */
#include "asn_internal.h"
