/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "PriMa-MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -R`
 */

#ifndef	_IntentSharingContainer_H_
#define	_IntentSharingContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "TrajectoryMCM.h"
#include "Heading.h"
#include "Speed.h"
#include "DriveDirection.h"
#include "VehicleLength.h"
#include "VehicleWidth.h"
#include "VehicleAutomationLevel.h"
#include "LanePosition.h"
#include "LaneID.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct LongitudinalAcceleration;
struct LateralAcceleration;
struct VerticalAcceleration;
struct YawRate;
struct WGS84Angle;

/* IntentSharingContainer */
typedef struct IntentSharingContainer {
	TrajectoryMCM_t	 plannedTrajectory;
	Heading_t	 heading;
	Speed_t	 speed;
	DriveDirection_t	 driveDirection;
	VehicleLength_t	 vehicleLength;
	VehicleWidth_t	 vehicleWidth;
	VehicleAutomationLevel_t	 vehicleAutomationLevel;
	struct LongitudinalAcceleration	*longitudinalAcceleration	/* OPTIONAL */;
	struct LateralAcceleration	*lateralAcceleration	/* OPTIONAL */;
	struct VerticalAcceleration	*verticalAcceleration	/* OPTIONAL */;
	struct YawRate	*yawRate	/* OPTIONAL */;
	struct WGS84Angle	*vehicleOrientationAngle	/* OPTIONAL */;
	LanePosition_t	*lanePosition	/* OPTIONAL */;
	LaneID_t	*roadID	/* OPTIONAL */;
	LaneID_t	*laneID	/* OPTIONAL */;
	LaneID_t	*laneIDEnd	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IntentSharingContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IntentSharingContainer;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "LongitudinalAcceleration.h"
#include "LateralAcceleration.h"
#include "VerticalAcceleration.h"
#include "YawRate.h"
#include "WGS84Angle.h"

#endif	/* _IntentSharingContainer_H_ */
#include "asn_internal.h"
