/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "TR103562v211-CPM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -R`
 */

#ifndef	_LongitudinalLanePositionConfidence_H_
#define	_LongitudinalLanePositionConfidence_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LongitudinalLanePositionConfidence {
	LongitudinalLanePositionConfidence_zeroPointZeroOneMeter	= 1,
	LongitudinalLanePositionConfidence_oneMeter	= 100,
	LongitudinalLanePositionConfidence_outOfRange	= 101,
	LongitudinalLanePositionConfidence_unavailable	= 102
} e_LongitudinalLanePositionConfidence;

/* LongitudinalLanePositionConfidence */
typedef long	 LongitudinalLanePositionConfidence_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LongitudinalLanePositionConfidence;
asn_struct_free_f LongitudinalLanePositionConfidence_free;
asn_struct_print_f LongitudinalLanePositionConfidence_print;
asn_constr_check_f LongitudinalLanePositionConfidence_constraint;
ber_type_decoder_f LongitudinalLanePositionConfidence_decode_ber;
der_type_encoder_f LongitudinalLanePositionConfidence_encode_der;
xer_type_decoder_f LongitudinalLanePositionConfidence_decode_xer;
xer_type_encoder_f LongitudinalLanePositionConfidence_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _LongitudinalLanePositionConfidence_H_ */
#include "asn_internal.h"
