/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "PriMa-MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -R`
 */

#ifndef	_ManeuverExecutionContainer_H_
#define	_ManeuverExecutionContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "McmCategory.h"
#include "PriorityManeuver.h"
#include "CooperationID.h"
#include "StationID.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ManeuverExecutionContainer */
typedef struct ManeuverExecutionContainer {
	McmCategory_t	 mcmCategory;
	PriorityManeuver_t	 priorityManeuver;
	CooperationID_t	 cooperationID;
	StationID_t	 cooperationVehicleID1;
	StationID_t	*cooperationVehicleID2	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ManeuverExecutionContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ManeuverExecutionContainer;

#ifdef __cplusplus
}
#endif

#endif	/* _ManeuverExecutionContainer_H_ */
#include "asn_internal.h"
