/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "PriMa-MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -R`
 */

#include "ManeuverExecutionContainer.h"

static asn_TYPE_member_t asn_MBR_ManeuverExecutionContainer_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ManeuverExecutionContainer, mcmCategory),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_McmCategory,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"mcmCategory"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ManeuverExecutionContainer, priorityManeuver),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PriorityManeuver,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"priorityManeuver"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ManeuverExecutionContainer, cooperationID),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CooperationID,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"cooperationID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ManeuverExecutionContainer, cooperationVehicleID1),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_StationID,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"cooperationVehicleID1"
		},
	{ ATF_POINTER, 1, offsetof(struct ManeuverExecutionContainer, cooperationVehicleID2),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_StationID,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"cooperationVehicleID2"
		},
};
static const ber_tlv_tag_t asn_DEF_ManeuverExecutionContainer_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ManeuverExecutionContainer_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* mcmCategory */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* priorityManeuver */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* cooperationID */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* cooperationVehicleID1 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* cooperationVehicleID2 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ManeuverExecutionContainer_specs_1 = {
	sizeof(struct ManeuverExecutionContainer),
	offsetof(struct ManeuverExecutionContainer, _asn_ctx),
	asn_MAP_ManeuverExecutionContainer_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ManeuverExecutionContainer = {
	"ManeuverExecutionContainer",
	"ManeuverExecutionContainer",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ManeuverExecutionContainer_tags_1,
	sizeof(asn_DEF_ManeuverExecutionContainer_tags_1)
		/sizeof(asn_DEF_ManeuverExecutionContainer_tags_1[0]), /* 1 */
	asn_DEF_ManeuverExecutionContainer_tags_1,	/* Same as above */
	sizeof(asn_DEF_ManeuverExecutionContainer_tags_1)
		/sizeof(asn_DEF_ManeuverExecutionContainer_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ManeuverExecutionContainer_1,
	5,	/* Elements count */
	&asn_SPC_ManeuverExecutionContainer_specs_1	/* Additional specs */
};

