/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "PriMa-MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -R`
 */

#ifndef	_ManeuverCoordinationMessage_H_
#define	_ManeuverCoordinationMessage_H_


#include "asn_application.h"

/* Including external dependencies */
#include "GenerationDeltaTime.h"
#include "McmParameters.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ManeuverCoordinationMessage */
typedef struct ManeuverCoordinationMessage {
	GenerationDeltaTime_t	 generationDeltaTime;
	McmParameters_t	 mcmParameters;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ManeuverCoordinationMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ManeuverCoordinationMessage;

#ifdef __cplusplus
}
#endif

#endif	/* _ManeuverCoordinationMessage_H_ */
#include "asn_internal.h"
