/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "PriMa-MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -R`
 */

#ifndef	_ManeuverNegotiationContainer_H_
#define	_ManeuverNegotiationContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "McmCategory.h"
#include "PriorityManeuver.h"
#include "CooperationTypeMCM.h"
#include "RequestID.h"
#include "TrajectoryMCM.h"
#include "Reason.h"
#include "ReasonReject.h"
#include "LaneID.h"
#include "CooperationCostTrajectory.h"
#include "NumberOfVehicles.h"
#include "StationID.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct TrajectoryMCM;

/* ManeuverNegotiationContainer */
typedef struct ManeuverNegotiationContainer {
	McmCategory_t	 mcmCategory;
	PriorityManeuver_t	 priorityManeuver;
	CooperationTypeMCM_t	 cooperationTypeMCM;
	RequestID_t	 requestID;
	TrajectoryMCM_t	 requestedTrajectory;
	TrajectoryMCM_t	 offeredTrajectory;
	struct TrajectoryMCM	*alternativeTrajectory	/* OPTIONAL */;
	Reason_t	*reasonRequest	/* OPTIONAL */;
	ReasonReject_t	*reasonReject	/* OPTIONAL */;
	LaneID_t	*laneID	/* OPTIONAL */;
	LaneID_t	*laneIDTrajEnd	/* OPTIONAL */;
	CooperationCostTrajectory_t	*cooperationCostTrajectory	/* OPTIONAL */;
	NumberOfVehicles_t	 numberOfVehicles;
	StationID_t	 negotiationVehicleID1;
	StationID_t	*negotiationVehicleID2	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ManeuverNegotiationContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ManeuverNegotiationContainer;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "TrajectoryMCM.h"

#endif	/* _ManeuverNegotiationContainer_H_ */
#include "asn_internal.h"
