/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "PriMa-MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -R`
 */

#include "ManeuverNegotiationContainer.h"

static asn_TYPE_member_t asn_MBR_ManeuverNegotiationContainer_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ManeuverNegotiationContainer, mcmCategory),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_McmCategory,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"mcmCategory"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ManeuverNegotiationContainer, priorityManeuver),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PriorityManeuver,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"priorityManeuver"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ManeuverNegotiationContainer, cooperationTypeMCM),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CooperationTypeMCM,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"cooperationTypeMCM"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ManeuverNegotiationContainer, requestID),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RequestID,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"requestID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ManeuverNegotiationContainer, requestedTrajectory),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TrajectoryMCM,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"requestedTrajectory"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ManeuverNegotiationContainer, offeredTrajectory),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TrajectoryMCM,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"offeredTrajectory"
		},
	{ ATF_POINTER, 6, offsetof(struct ManeuverNegotiationContainer, alternativeTrajectory),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TrajectoryMCM,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"alternativeTrajectory"
		},
	{ ATF_POINTER, 5, offsetof(struct ManeuverNegotiationContainer, reasonRequest),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Reason,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"reasonRequest"
		},
	{ ATF_POINTER, 4, offsetof(struct ManeuverNegotiationContainer, reasonReject),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ReasonReject,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"reasonReject"
		},
	{ ATF_POINTER, 3, offsetof(struct ManeuverNegotiationContainer, laneID),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LaneID,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"laneID"
		},
	{ ATF_POINTER, 2, offsetof(struct ManeuverNegotiationContainer, laneIDTrajEnd),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LaneID,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"laneIDTrajEnd"
		},
	{ ATF_POINTER, 1, offsetof(struct ManeuverNegotiationContainer, cooperationCostTrajectory),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CooperationCostTrajectory,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"cooperationCostTrajectory"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ManeuverNegotiationContainer, numberOfVehicles),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NumberOfVehicles,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"numberOfVehicles"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ManeuverNegotiationContainer, negotiationVehicleID1),
		(ASN_TAG_CLASS_CONTEXT | (13 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_StationID,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"negotiationVehicleID1"
		},
	{ ATF_POINTER, 1, offsetof(struct ManeuverNegotiationContainer, negotiationVehicleID2),
		(ASN_TAG_CLASS_CONTEXT | (14 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_StationID,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"negotiationVehicleID2"
		},
};
static const ber_tlv_tag_t asn_DEF_ManeuverNegotiationContainer_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ManeuverNegotiationContainer_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* mcmCategory */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* priorityManeuver */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* cooperationTypeMCM */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* requestID */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* requestedTrajectory */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* offeredTrajectory */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* alternativeTrajectory */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* reasonRequest */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* reasonReject */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* laneID */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 }, /* laneIDTrajEnd */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 11, 0, 0 }, /* cooperationCostTrajectory */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 12, 0, 0 }, /* numberOfVehicles */
    { (ASN_TAG_CLASS_CONTEXT | (13 << 2)), 13, 0, 0 }, /* negotiationVehicleID1 */
    { (ASN_TAG_CLASS_CONTEXT | (14 << 2)), 14, 0, 0 } /* negotiationVehicleID2 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ManeuverNegotiationContainer_specs_1 = {
	sizeof(struct ManeuverNegotiationContainer),
	offsetof(struct ManeuverNegotiationContainer, _asn_ctx),
	asn_MAP_ManeuverNegotiationContainer_tag2el_1,
	15,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ManeuverNegotiationContainer = {
	"ManeuverNegotiationContainer",
	"ManeuverNegotiationContainer",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ManeuverNegotiationContainer_tags_1,
	sizeof(asn_DEF_ManeuverNegotiationContainer_tags_1)
		/sizeof(asn_DEF_ManeuverNegotiationContainer_tags_1[0]), /* 1 */
	asn_DEF_ManeuverNegotiationContainer_tags_1,	/* Same as above */
	sizeof(asn_DEF_ManeuverNegotiationContainer_tags_1)
		/sizeof(asn_DEF_ManeuverNegotiationContainer_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ManeuverNegotiationContainer_1,
	15,	/* Elements count */
	&asn_SPC_ManeuverNegotiationContainer_specs_1	/* Additional specs */
};

