/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "PriMa-MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -R`
 */

#ifndef	_McmCategory_H_
#define	_McmCategory_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum McmCategory {
	McmCategory_request	= 0,
	McmCategory_accept	= 1,
	McmCategory_reject	= 2,
	McmCategory_offer	= 3,
	McmCategory_confirm	= 4,
	McmCategory_execute	= 5,
	McmCategory_cancel	= 6,
	McmCategory_abort	= 7,
	McmCategory_cascadingRequest	= 8,
	McmCategory_cascadingAccept	= 9,
	McmCategory_cascadingReject	= 10,
	McmCategory_cascadingExecute	= 11
} e_McmCategory;

/* McmCategory */
typedef long	 McmCategory_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_McmCategory;
asn_struct_free_f McmCategory_free;
asn_struct_print_f McmCategory_print;
asn_constr_check_f McmCategory_constraint;
ber_type_decoder_f McmCategory_decode_ber;
der_type_encoder_f McmCategory_encode_der;
xer_type_decoder_f McmCategory_decode_xer;
xer_type_encoder_f McmCategory_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _McmCategory_H_ */
#include "asn_internal.h"
