/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "PriMa-MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -R`
 */

#ifndef	_McmParameters_H_
#define	_McmParameters_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BasicContainerMCM.h"
#include "IntentSharingContainer.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ManeuverNegotiationContainer;
struct ManeuverExecutionContainer;

/* McmParameters */
typedef struct McmParameters {
	BasicContainerMCM_t	 basicContainerMCM;
	IntentSharingContainer_t	 intentionSharingContainer;
	struct ManeuverNegotiationContainer	*maneuverNegotiationContainer	/* OPTIONAL */;
	struct ManeuverExecutionContainer	*maneuverExecutionContainer	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} McmParameters_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_McmParameters;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ManeuverNegotiationContainer.h"
#include "ManeuverExecutionContainer.h"

#endif	/* _McmParameters_H_ */
#include "asn_internal.h"
