/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "TR103562v211-CPM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -R`
 */

#include "NodeOffsetPointZ.h"

static asn_TYPE_member_t asn_MBR_NodeOffsetPointZ_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct NodeOffsetPointZ, choice.node_Z1),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Offset_B10,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"node-Z1"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct NodeOffsetPointZ, choice.node_Z2),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Offset_B11,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"node-Z2"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct NodeOffsetPointZ, choice.node_Z3),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Offset_B12,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"node-Z3"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct NodeOffsetPointZ, choice.node_Z4),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Offset_B13,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"node-Z4"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct NodeOffsetPointZ, choice.node_Z5),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Offset_B14,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"node-Z5"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct NodeOffsetPointZ, choice.node_Z6),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Offset_B16,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"node-Z6"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_NodeOffsetPointZ_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* node-Z1 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* node-Z2 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* node-Z3 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* node-Z4 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* node-Z5 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* node-Z6 */
};
static asn_CHOICE_specifics_t asn_SPC_NodeOffsetPointZ_specs_1 = {
	sizeof(struct NodeOffsetPointZ),
	offsetof(struct NodeOffsetPointZ, _asn_ctx),
	offsetof(struct NodeOffsetPointZ, present),
	sizeof(((struct NodeOffsetPointZ *)0)->present),
	asn_MAP_NodeOffsetPointZ_tag2el_1,
	6,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_NodeOffsetPointZ = {
	"NodeOffsetPointZ",
	"NodeOffsetPointZ",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_NodeOffsetPointZ_1,
	6,	/* Elements count */
	&asn_SPC_NodeOffsetPointZ_specs_1	/* Additional specs */
};

