/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "TR103562v211-CPM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -R`
 */

#ifndef	_NumberOfPerceivedObjects_H_
#define	_NumberOfPerceivedObjects_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* NumberOfPerceivedObjects */
typedef long	 NumberOfPerceivedObjects_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NumberOfPerceivedObjects;
asn_struct_free_f NumberOfPerceivedObjects_free;
asn_struct_print_f NumberOfPerceivedObjects_print;
asn_constr_check_f NumberOfPerceivedObjects_constraint;
ber_type_decoder_f NumberOfPerceivedObjects_decode_ber;
der_type_encoder_f NumberOfPerceivedObjects_encode_der;
xer_type_decoder_f NumberOfPerceivedObjects_decode_xer;
xer_type_encoder_f NumberOfPerceivedObjects_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _NumberOfPerceivedObjects_H_ */
#include "asn_internal.h"
