/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "TR103562v211-CPM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -R`
 */

#include "ObjectClass.h"

static asn_TYPE_member_t asn_MBR_class_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ObjectClass__Class, choice.vehicle),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VehicleSubclass,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"vehicle"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ObjectClass__Class, choice.person),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PersonSubclass,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"person"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ObjectClass__Class, choice.animal),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AnimalSubclass,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"animal"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ObjectClass__Class, choice.other),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OtherSubclass,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"other"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_class_tag2el_3[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* vehicle */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* person */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* animal */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* other */
};
static asn_CHOICE_specifics_t asn_SPC_class_specs_3 = {
	sizeof(struct ObjectClass__Class),
	offsetof(struct ObjectClass__Class, _asn_ctx),
	offsetof(struct ObjectClass__Class, present),
	sizeof(((struct ObjectClass__Class *)0)->present),
	asn_MAP_class_tag2el_3,
	4,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_class_3 = {
	"class",
	"class",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_class_3,
	4,	/* Elements count */
	&asn_SPC_class_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ObjectClass_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ObjectClass, confidence),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ClassConfidence,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"confidence"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ObjectClass, Class),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_class_3,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"class"
		},
};
static const ber_tlv_tag_t asn_DEF_ObjectClass_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ObjectClass_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* confidence */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* class */
};
static asn_SEQUENCE_specifics_t asn_SPC_ObjectClass_specs_1 = {
	sizeof(struct ObjectClass),
	offsetof(struct ObjectClass, _asn_ctx),
	asn_MAP_ObjectClass_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ObjectClass = {
	"ObjectClass",
	"ObjectClass",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ObjectClass_tags_1,
	sizeof(asn_DEF_ObjectClass_tags_1)
		/sizeof(asn_DEF_ObjectClass_tags_1[0]), /* 1 */
	asn_DEF_ObjectClass_tags_1,	/* Same as above */
	sizeof(asn_DEF_ObjectClass_tags_1)
		/sizeof(asn_DEF_ObjectClass_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ObjectClass_1,
	2,	/* Elements count */
	&asn_SPC_ObjectClass_specs_1	/* Additional specs */
};

