/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "TR103562v211-CPM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -R`
 */

#ifndef	_ObjectAge_H_
#define	_ObjectAge_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ObjectAge {
	ObjectAge_oneMiliSec	= 1
} e_ObjectAge;

/* ObjectAge */
typedef long	 ObjectAge_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ObjectAge;
asn_struct_free_f ObjectAge_free;
asn_struct_print_f ObjectAge_print;
asn_constr_check_f ObjectAge_constraint;
ber_type_decoder_f ObjectAge_decode_ber;
der_type_encoder_f ObjectAge_encode_der;
xer_type_decoder_f ObjectAge_decode_xer;
xer_type_encoder_f ObjectAge_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ObjectAge_H_ */
#include "asn_internal.h"
