/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "TR103562v211-CPM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -R`
 */

#ifndef	_ObjectDimensionValue_H_
#define	_ObjectDimensionValue_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ObjectDimensionValue {
	ObjectDimensionValue_zeroPointOneMeter	= 1,
	ObjectDimensionValue_oneMeter	= 10
} e_ObjectDimensionValue;

/* ObjectDimensionValue */
typedef long	 ObjectDimensionValue_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ObjectDimensionValue;
asn_struct_free_f ObjectDimensionValue_free;
asn_struct_print_f ObjectDimensionValue_print;
asn_constr_check_f ObjectDimensionValue_constraint;
ber_type_decoder_f ObjectDimensionValue_decode_ber;
der_type_encoder_f ObjectDimensionValue_encode_der;
xer_type_decoder_f ObjectDimensionValue_decode_xer;
xer_type_encoder_f ObjectDimensionValue_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ObjectDimensionValue_H_ */
#include "asn_internal.h"
