/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "TR103562v211-CPM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -R`
 */

#ifndef	_ObjectDimension_H_
#define	_ObjectDimension_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ObjectDimensionValue.h"
#include "ObjectDimensionConfidence.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ObjectDimension */
typedef struct ObjectDimension {
	ObjectDimensionValue_t	 value;
	ObjectDimensionConfidence_t	 confidence;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ObjectDimension_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ObjectDimension;

#ifdef __cplusplus
}
#endif

#endif	/* _ObjectDimension_H_ */
#include "asn_internal.h"
