/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "TR103562v211-CPM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -R`
 */

#ifndef	_OffsetPoint_H_
#define	_OffsetPoint_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NodeOffsetPointXY.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NodeOffsetPointZ;

/* OffsetPoint */
typedef struct OffsetPoint {
	NodeOffsetPointXY_t	 nodeOffsetPointxy;
	struct NodeOffsetPointZ	*nodeOffsetPointZ	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} OffsetPoint_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OffsetPoint;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "NodeOffsetPointZ.h"

#endif	/* _OffsetPoint_H_ */
#include "asn_internal.h"
