/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "TR103562v211-CPM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -R`
 */

#ifndef	_OriginatingRSUContainer_H_
#define	_OriginatingRSUContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "IntersectionReferenceID.h"
#include "RoadSegmentReferenceID.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum OriginatingRSUContainer_PR {
	OriginatingRSUContainer_PR_NOTHING,	/* No components present */
	OriginatingRSUContainer_PR_intersectionReferenceId,
	OriginatingRSUContainer_PR_roadSegmentReferenceId,
	/* Extensions may appear below */
	
} OriginatingRSUContainer_PR;

/* OriginatingRSUContainer */
typedef struct OriginatingRSUContainer {
	OriginatingRSUContainer_PR present;
	union OriginatingRSUContainer_u {
		IntersectionReferenceID_t	 intersectionReferenceId;
		RoadSegmentReferenceID_t	 roadSegmentReferenceId;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} OriginatingRSUContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OriginatingRSUContainer;

#ifdef __cplusplus
}
#endif

#endif	/* _OriginatingRSUContainer_H_ */
#include "asn_internal.h"
