/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "TR103562v211-CPM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -R`
 */

#ifndef	_OtherSublassType_H_
#define	_OtherSublassType_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum OtherSublassType {
	OtherSublassType_unknown	= 0,
	OtherSublassType_roadSideUnit	= 1
} e_OtherSublassType;

/* OtherSublassType */
typedef long	 OtherSublassType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OtherSublassType;
asn_struct_free_f OtherSublassType_free;
asn_struct_print_f OtherSublassType_print;
asn_constr_check_f OtherSublassType_constraint;
ber_type_decoder_f OtherSublassType_decode_ber;
der_type_encoder_f OtherSublassType_encode_der;
xer_type_decoder_f OtherSublassType_decode_xer;
xer_type_encoder_f OtherSublassType_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _OtherSublassType_H_ */
#include "asn_internal.h"
