/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "TR103562v211-CPM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -R`
 */

#ifndef	_OtherSubclass_H_
#define	_OtherSubclass_H_


#include "asn_application.h"

/* Including external dependencies */
#include "OtherSublassType.h"
#include "ClassConfidence.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* OtherSubclass */
typedef struct OtherSubclass {
	OtherSublassType_t	 type	/* DEFAULT 0 */;
	ClassConfidence_t	 confidence	/* DEFAULT 0 */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} OtherSubclass_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OtherSubclass;

#ifdef __cplusplus
}
#endif

#endif	/* _OtherSubclass_H_ */
#include "asn_internal.h"
