/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "TR103562v211-CPM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -R`
 */

#ifndef	_PerceivedObjectContainer_H_
#define	_PerceivedObjectContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PerceivedObject;

/* PerceivedObjectContainer */
typedef struct PerceivedObjectContainer {
	A_SEQUENCE_OF(struct PerceivedObject) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PerceivedObjectContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PerceivedObjectContainer;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PerceivedObject.h"

#endif	/* _PerceivedObjectContainer_H_ */
#include "asn_internal.h"
