/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "TR103562v211-CPM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -R`
 */

#ifndef	_PerceivedObjectContainerSegmentInfo_H_
#define	_PerceivedObjectContainerSegmentInfo_H_


#include "asn_application.h"

/* Including external dependencies */
#include "SegmentCount.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* PerceivedObjectContainerSegmentInfo */
typedef struct PerceivedObjectContainerSegmentInfo {
	SegmentCount_t	 totalMsgSegments;
	SegmentCount_t	 thisSegmentNum;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PerceivedObjectContainerSegmentInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PerceivedObjectContainerSegmentInfo;

#ifdef __cplusplus
}
#endif

#endif	/* _PerceivedObjectContainerSegmentInfo_H_ */
#include "asn_internal.h"
