/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "PriMa-MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -R`
 */

#ifndef	_PriorityManeuver_H_
#define	_PriorityManeuver_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PriorityManeuver {
	PriorityManeuver_low	= 0,
	PriorityManeuver_medium	= 1,
	PriorityManeuver_high	= 2,
	PriorityManeuver_emergency	= 3
} e_PriorityManeuver;

/* PriorityManeuver */
typedef long	 PriorityManeuver_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PriorityManeuver;
asn_struct_free_f PriorityManeuver_free;
asn_struct_print_f PriorityManeuver_print;
asn_constr_check_f PriorityManeuver_constraint;
ber_type_decoder_f PriorityManeuver_decode_ber;
der_type_encoder_f PriorityManeuver_encode_der;
xer_type_decoder_f PriorityManeuver_decode_xer;
xer_type_encoder_f PriorityManeuver_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _PriorityManeuver_H_ */
#include "asn_internal.h"
