/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "PriMa-MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -R`
 */

#ifndef	_Reason_H_
#define	_Reason_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Reason {
	Reason_accelerate	= 0,
	Reason_decelerate	= 1,
	Reason_merging	= 2,
	Reason_laneChange	= 3,
	Reason_overtaking	= 4
} e_Reason;

/* Reason */
typedef long	 Reason_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Reason;
asn_struct_free_f Reason_free;
asn_struct_print_f Reason_print;
asn_constr_check_f Reason_constraint;
ber_type_decoder_f Reason_decode_ber;
der_type_encoder_f Reason_encode_der;
xer_type_decoder_f Reason_decode_xer;
xer_type_encoder_f Reason_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Reason_H_ */
#include "asn_internal.h"
