/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "TR103562v211-CPM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -R`
 */

#ifndef	_RefPointId_H_
#define	_RefPointId_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RefPointId */
typedef long	 RefPointId_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RefPointId;
asn_struct_free_f RefPointId_free;
asn_struct_print_f RefPointId_print;
asn_constr_check_f RefPointId_constraint;
ber_type_decoder_f RefPointId_decode_ber;
der_type_encoder_f RefPointId_encode_der;
xer_type_decoder_f RefPointId_decode_xer;
xer_type_encoder_f RefPointId_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _RefPointId_H_ */
#include "asn_internal.h"
