/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "ISO_TS_19091_CPM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -R`
 */

#ifndef	_RoadSegmentID_H_
#define	_RoadSegmentID_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RoadSegmentID */
typedef long	 RoadSegmentID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RoadSegmentID;
asn_struct_free_f RoadSegmentID_free;
asn_struct_print_f RoadSegmentID_print;
asn_constr_check_f RoadSegmentID_constraint;
ber_type_decoder_f RoadSegmentID_decode_ber;
der_type_encoder_f RoadSegmentID_encode_der;
xer_type_decoder_f RoadSegmentID_decode_xer;
xer_type_encoder_f RoadSegmentID_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _RoadSegmentID_H_ */
#include "asn_internal.h"
