/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "TR103562v211-CPM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -R`
 */

#ifndef	_SemiRangeLength_H_
#define	_SemiRangeLength_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SemiRangeLength {
	SemiRangeLength_zeroPointOneMeter	= 1,
	SemiRangeLength_oneMeter	= 10
} e_SemiRangeLength;

/* SemiRangeLength */
typedef long	 SemiRangeLength_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SemiRangeLength;
asn_struct_free_f SemiRangeLength_free;
asn_struct_print_f SemiRangeLength_print;
asn_constr_check_f SemiRangeLength_constraint;
ber_type_decoder_f SemiRangeLength_decode_ber;
der_type_encoder_f SemiRangeLength_encode_der;
xer_type_decoder_f SemiRangeLength_decode_xer;
xer_type_encoder_f SemiRangeLength_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _SemiRangeLength_H_ */
#include "asn_internal.h"
