/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "TR103562v211-CPM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -R`
 */

#ifndef	_SensorIdList_H_
#define	_SensorIdList_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Identifier.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SensorIdList */
typedef struct SensorIdList {
	A_SEQUENCE_OF(Identifier_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SensorIdList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SensorIdList;

#ifdef __cplusplus
}
#endif

#endif	/* _SensorIdList_H_ */
#include "asn_internal.h"
