/*
 * Generated by asn1c; locally adapted to Vanetza's current ASN.1 descriptor ABI.
 * From ASN.1 module "ITS-Container"
 * 	found in "TS102894-2v131-CDD.asn"
 */

#include "StationID.h"

int
StationID_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	unsigned long value;

	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}

	value = *(const unsigned long *)sptr;

	if(value <= 4294967295UL) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

/*
 * This type is implemented using NativeInteger,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_StationID_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32,  32,  0,  4294967295UL }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static const ber_tlv_tag_t asn_DEF_StationID_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (2 << 2))
};
static const asn_INTEGER_specifics_t asn_SPC_StationID_specs_1 = {
	0,	/* "tag" => N; sorted by tag */
	0,	/* N => "tag"; sorted by N */
	0,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	0,	/* Strict enumeration */
	0,	/* Native long size */
	1	/* Unsigned representation */
};
asn_TYPE_descriptor_t asn_DEF_StationID = {
	"StationID",
	"StationID",
	&asn_OP_NativeInteger,
	asn_DEF_StationID_tags_1,
	sizeof(asn_DEF_StationID_tags_1)
		/sizeof(asn_DEF_StationID_tags_1[0]), /* 1 */
	asn_DEF_StationID_tags_1,	/* Same as above */
	sizeof(asn_DEF_StationID_tags_1)
		/sizeof(asn_DEF_StationID_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_StationID_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		StationID_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_StationID_specs_1	/* Additional specs */
};
