/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "TR103562v211-CPM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -R`
 */

#include "StationDataContainer.h"

static asn_TYPE_member_t asn_MBR_StationDataContainer_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct StationDataContainer, choice.originatingVehicleContainer),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OriginatingVehicleContainer,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"originatingVehicleContainer"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct StationDataContainer, choice.originatingRSUContainer),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_OriginatingRSUContainer,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"originatingRSUContainer"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_StationDataContainer_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* originatingVehicleContainer */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* originatingRSUContainer */
};
static asn_CHOICE_specifics_t asn_SPC_StationDataContainer_specs_1 = {
	sizeof(struct StationDataContainer),
	offsetof(struct StationDataContainer, _asn_ctx),
	offsetof(struct StationDataContainer, present),
	sizeof(((struct StationDataContainer *)0)->present),
	asn_MAP_StationDataContainer_tag2el_1,
	2,	/* Count of tags in the map */
	0,
	2	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_StationDataContainer = {
	"StationDataContainer",
	"StationDataContainer",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_StationDataContainer_1,
	2,	/* Elements count */
	&asn_SPC_StationDataContainer_specs_1	/* Additional specs */
};

