/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "TR103562v211-CPM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -R`
 */

#ifndef	_TrailerData_H_
#define	_TrailerData_H_


#include "asn_application.h"

/* Including external dependencies */
#include "RefPointId.h"
#include "HitchPointOffset.h"
#include "FrontOverhang.h"
#include "RearOverhang.h"
#include "VehicleWidth.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CartesianAngle;

/* TrailerData */
typedef struct TrailerData {
	RefPointId_t	 refPointId;
	HitchPointOffset_t	 hitchPointOffset;
	FrontOverhang_t	 frontOverhang;
	RearOverhang_t	 rearOverhang;
	VehicleWidth_t	*trailerWidth	/* OPTIONAL */;
	struct CartesianAngle	*hitchAngle	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TrailerData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TrailerData;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CartesianAngle.h"

#endif	/* _TrailerData_H_ */
#include "asn_internal.h"
