/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "TR103562v211-CPM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -R`
 */

#ifndef	_VehicleSensorProperties_H_
#define	_VehicleSensorProperties_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Range.h"
#include "CartesianAngleValue.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* VehicleSensorProperties */
typedef struct VehicleSensorProperties {
	Range_t	 range;
	CartesianAngleValue_t	 horizontalOpeningAngleStart;
	CartesianAngleValue_t	 horizontalOpeningAngleEnd;
	CartesianAngleValue_t	*verticalOpeningAngleStart	/* OPTIONAL */;
	CartesianAngleValue_t	*verticalOpeningAngleEnd	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VehicleSensorProperties_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehicleSensorProperties;

#ifdef __cplusplus
}
#endif

#endif	/* _VehicleSensorProperties_H_ */
#include "asn_internal.h"
