/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "PriMa-MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -R`
 */

#ifndef	_VehicleAutomationLevel_H_
#define	_VehicleAutomationLevel_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VehicleAutomationLevel {
	VehicleAutomationLevel_notAvailable	= 0,
	VehicleAutomationLevel_saeLevel1	= 1,
	VehicleAutomationLevel_saeLevel2	= 2,
	VehicleAutomationLevel_saeLevel3	= 3,
	VehicleAutomationLevel_saeLevel4	= 4,
	VehicleAutomationLevel_saeLevel5	= 5
} e_VehicleAutomationLevel;

/* VehicleAutomationLevel */
typedef long	 VehicleAutomationLevel_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehicleAutomationLevel;
asn_struct_free_f VehicleAutomationLevel_free;
asn_struct_print_f VehicleAutomationLevel_print;
asn_constr_check_f VehicleAutomationLevel_constraint;
ber_type_decoder_f VehicleAutomationLevel_decode_ber;
der_type_encoder_f VehicleAutomationLevel_encode_der;
xer_type_decoder_f VehicleAutomationLevel_decode_xer;
xer_type_encoder_f VehicleAutomationLevel_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _VehicleAutomationLevel_H_ */
#include "asn_internal.h"
