/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "TR103562v211-CPM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -R`
 */

#include "VehicleSubclass.h"

static int asn_DFL_2_set_0(int set_value, void **sptr) {
	VehicleSubclassType_t *st = *sptr;
	
	if(!st) {
		if(!set_value) return -1;	/* Not a default value */
		st = (*sptr = CALLOC(1, sizeof(*st)));
		if(!st) return -1;
	}
	
	if(set_value) {
		/* Install default value 0 */
		*st = 0;
		return 0;
	} else {
		/* Test default value 0 */
		return (*st == 0);
	}
}
static int asn_DFL_3_set_0(int set_value, void **sptr) {
	ClassConfidence_t *st = *sptr;
	
	if(!st) {
		if(!set_value) return -1;	/* Not a default value */
		st = (*sptr = CALLOC(1, sizeof(*st)));
		if(!st) return -1;
	}
	
	if(set_value) {
		/* Install default value 0 */
		*st = 0;
		return 0;
	} else {
		/* Test default value 0 */
		return (*st == 0);
	}
}
static asn_TYPE_member_t asn_MBR_VehicleSubclass_1[] = {
	{ ATF_NOFLAGS, 2, offsetof(struct VehicleSubclass, type),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VehicleSubclassType,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		asn_DFL_2_set_0,	/* DEFAULT 0 */
		"type"
		},
	{ ATF_NOFLAGS, 1, offsetof(struct VehicleSubclass, confidence),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ClassConfidence,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		asn_DFL_3_set_0,	/* DEFAULT 0 */
		"confidence"
		},
};
static const ber_tlv_tag_t asn_DEF_VehicleSubclass_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_VehicleSubclass_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* type */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* confidence */
};
static asn_SEQUENCE_specifics_t asn_SPC_VehicleSubclass_specs_1 = {
	sizeof(struct VehicleSubclass),
	offsetof(struct VehicleSubclass, _asn_ctx),
	asn_MAP_VehicleSubclass_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_VehicleSubclass = {
	"VehicleSubclass",
	"VehicleSubclass",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_VehicleSubclass_tags_1,
	sizeof(asn_DEF_VehicleSubclass_tags_1)
		/sizeof(asn_DEF_VehicleSubclass_tags_1[0]), /* 1 */
	asn_DEF_VehicleSubclass_tags_1,	/* Same as above */
	sizeof(asn_DEF_VehicleSubclass_tags_1)
		/sizeof(asn_DEF_VehicleSubclass_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_VehicleSubclass_1,
	2,	/* Elements count */
	&asn_SPC_VehicleSubclass_specs_1	/* Additional specs */
};

