/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "TR103562v211-CPM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -R`
 */

#ifndef	_WGS84Angle_H_
#define	_WGS84Angle_H_


#include "asn_application.h"

/* Including external dependencies */
#include "WGS84AngleValue.h"
#include "AngleConfidence.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* WGS84Angle */
typedef struct WGS84Angle {
	WGS84AngleValue_t	 value;
	AngleConfidence_t	 confidence;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} WGS84Angle_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_WGS84Angle;

#ifdef __cplusplus
}
#endif

#endif	/* _WGS84Angle_H_ */
#include "asn_internal.h"
